name = "game-play-randomiser"
main = "worker.js"
compatibility_date = "2024-09-23"

[vars]
ENVIRONMENT = "production"

[assets]
directory = "./public"
binding = "ASSETS"

[[routes]]
pattern = "gameplay.hultberg.org"
custom_domain = true